export const FakeRecettes = [
  {
    id: 1,
    mainText: 'Poulet au air fryer',
    subText: 'Pas sec, très bon !',
    ingredientsPrincipaux: ['Poulet'],
    isVegan: false,
    img: 'poulet',
    tempsPreparation: 25,
    difficulte: 'Facile',
    note: 4.5,
    ingredients: [
      '2 blancs de poulet',
      '1 c.à.s d’huile d’olive',
      '1 c.à.c de paprika',
      'Sel, poivre',
    ],
    preparation: [
      'Préchauffer l’air fryer à 180°C.',
      'Découper le poulet en morceaux.',
      'Mélanger avec huile, paprika, sel et poivre.',
      'Cuire 18 minutes en remuant à mi-cuisson.',
    ],
  },
  {
    id: 2,
    mainText: 'Frites au air fryer',
    subText: 'Vraiment pas mal !',
    ingredientsPrincipaux: ['Patate'],
    isVegan: true,
    img: 'frites',
    tempsPreparation: 20,
    difficulte: 'Facile',
    note: 4.2,
    ingredients: [
      '4 pommes de terre',
      '1 c.à.s d’huile',
      'Sel',
    ],
    preparation: [
      'Éplucher et couper les pommes de terre en frites.',
      'Tremper dans l’eau froide 10 minutes.',
      'Sécher, mélanger avec l’huile et le sel.',
      'Cuire 20 minutes à 200°C en secouant à mi-cuisson.',
    ],
  },
  {
    id: 3,
    mainText: 'Piperade au air fryer',
    subText: 'Très goutu !',
    ingredientsPrincipaux: ['Tomate', 'Poivron', 'Oignon'],
    isVegan: true,
    img: 'poivron',
    tempsPreparation: 35,
    difficulte: 'Moyen',
    note: 4.8,
    ingredients: [
      '2 poivrons',
      '3 tomates',
      '1 oignon',
      '1 gousse d’ail',
      'Huile d’olive',
    ],
    preparation: [
      'Émincer l’oignon et l’ail.',
      'Couper les tomates et poivrons en dés.',
      'Mélanger avec un filet d’huile.',
      'Cuire 30 minutes à 180°C en remuant 2 fois.',
    ],
  },
  {
    id: 4,
    mainText: 'Patates au air fryer',
    subText: 'Le goût est intense !',
    ingredientsPrincipaux: ['Patate'],
    isVegan: true,
    img: 'patate',
    tempsPreparation: 30,
    difficulte: 'Facile',
    note: 4.0,
    ingredients: [
      '5 petites pommes de terre',
      '1 c.à.s d’huile',
      'Herbes de Provence',
      'Sel, poivre',
    ],
    preparation: [
      'Laver et couper les pommes de terre en cubes.',
      'Assaisonner avec huile, herbes, sel et poivre.',
      'Mettre dans l’air fryer 25-30 min à 200°C.',
    ],
  },
  {
    id: 5,
    mainText: 'Brocolis croustillants',
    subText: 'Un snack healthy et rapide',
    ingredientsPrincipaux: ['Brocoli'],
    isVegan: true,
    img: 'brocoli',
    tempsPreparation: 15,
    difficulte: 'Facile',
    note: 4.6,
    ingredients: [
      '1 tête de brocoli',
      '1 c.à.s d’huile d’olive',
      '1 pincée de sel',
      '1 c.à.s de parmesan vegan (optionnel)',
    ],
    preparation: [
      'Couper le brocoli en petits bouquets.',
      'Mélanger avec l’huile, le sel et le parmesan.',
      'Cuire 10-12 minutes à 200°C.',
    ],
  },
  {
    id: 6,
    mainText: 'Saumon grillé',
    subText: 'Parfaitement tendre',
    ingredientsPrincipaux: ['Poisson'],
    isVegan: false,
    img: 'saumon',
    tempsPreparation: 28,
    difficulte: 'Moyen',
    note: 4.7,
    ingredients: [
      '2 pavés de saumon',
      '1 filet de jus de citron',
      '1 c.à.s d’huile',
      'Sel, poivre',
    ],
    preparation: [
      'Assaisonner le saumon avec huile, citron, sel et poivre.',
      'Préchauffer l’air fryer à 180°C.',
      'Cuire 12-15 minutes selon l’épaisseur.',
    ],
  },
  {
    id: 7,
    mainText: 'Tofu croustillant',
    subText: 'Un classique vegan délicieux',
    ingredientsPrincipaux: ['Tofu'],
    isVegan: true,
    img: 'tofu',
    tempsPreparation: 22,
    difficulte: 'Facile',
    note: 4.3,
    ingredients: [
      '200g de tofu ferme',
      '2 c.à.s de sauce soja',
      '1 c.à.s d’huile',
      '1 c.à.c de fécule de maïs',
    ],
    preparation: [
      'Couper le tofu en dés.',
      'Mélanger avec soja, huile et fécule.',
      'Cuire 20 minutes à 200°C en secouant à mi-cuisson.',
    ],
  },
  {
  id: 8,
  mainText: 'Poulet au curry et riz aux légumes',
  subText: 'Un plat complet et savoureux',
  ingredientsPrincipaux: ['Poulet', 'Riz', 'Carotte', 'Curry'], // protéine, féculent, légume, épice
  isVegan: false,
  img: 'poulet_curry', // pense à ajouter cette image dans ton dossier assets/png
  tempsPreparation: 40,
  difficulte: 'Moyen',
  note: 4.9,
  ingredients: [
    '200g de poulet',
    '100g de riz',
    '1 carotte',
    '1 c. à café de curry',
    'Sel, poivre'
  ],
  preparation: [
    'Couper le poulet en morceaux',
    'Cuire le riz',
    'Faire revenir les légumes',
    'Ajouter le poulet et le curry',
    'Assaisonner avec sel et poivre'
  ],
},


];
